#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Cli;

use Lkrms\Cli\CliApplication;
use Lkrms\Tests\Cli\Command\TestOptions;

require __DIR__ . '/../../vendor/autoload.php';

(new CliApplication(dirname(__DIR__)))
    ->command(['test', 'options'], TestOptions::class)
    ->command(['sync'], TestOptions::class)
    ->runAndExit();
