#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Cli;

use Lkrms\Cli\Cli;
use Lkrms\Err\Err;
use Lkrms\Tests\Cli\Command\TestOptions;
use Lkrms\Util\Env;
use Throwable;

$loader = require (__DIR__ . "/../../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__ . "/..");

Err::handleErrors();

Env::load(__DIR__ . "/../.env");

$exceptions = [];

// Register TestOptions as the only command
TestOptions::register([]);

try
{
    // Try to register it under its usual name
    TestOptions::register(["test", "options"]);
}
catch (Throwable $ex)
{
    $exceptions[] = $ex;
}

print_r([
    'exceptions' => array_map(function (Throwable $ex) { return $ex->getMessage(); }, $exceptions),
]);

$status = Cli::run();
exit ($status);
