<?php declare(strict_types=1);

namespace Salient\Polyfill\StreamWrapper;

interface HasDirectoryHandles extends StreamWrapperInterface
{
    /**
     * Close directory handle
     *
     * This method is called in response to {@see closedir()}.
     *
     * Any resources which were locked, or allocated, during opening and use of
     * the directory stream should be released.
     *
     * @return bool `true` on success or `false` on failure.
     */
    public function dir_closedir(): bool;

    /**
     * Open directory handle
     *
     * This method is called in response to {@see opendir()}.
     *
     * @param string $path Specifies the URL that was passed to
     * {@see opendir()}.
     * @return bool `true` on success or `false` on failure.
     */
    public function dir_opendir(string $path, int $options): bool;

    /**
     * Read entry from directory handle
     *
     * This method is called in response to {@see readdir()}.
     *
     * @return string|false The next filename, or `false` if there is no next
     * file.
     */
    public function dir_readdir();

    /**
     * Rewind directory handle
     *
     * This method is called in response to {@see rewinddir()}.
     *
     * Should reset the output generated by
     * {@see HasDirectoryHandles::dir_readdir()}, i.e. the next call to
     * {@see HasDirectoryHandles::dir_readdir()} should return the first entry
     * in the location returned by {@see HasDirectoryHandles::dir_opendir()}.
     *
     * @return bool `true` on success or `false` on failure.
     */
    public function dir_rewinddir(): bool;
}
