<?php declare(strict_types=1);

namespace Salient\Tests\Polyfill;

use Salient\Polyfill\PhpToken;
use Salient\Tests\TestCase;
use Salient\Utility\Get;
use Salient\Utility\Str;
use TypeError;

abstract class PhpTokenTestCase extends TestCase
{
    private const CODE = <<<'PHP'
<div><?php
namespace Foo\Bar;

use Foo\{A as AA, B AS BB};

class A
{
    const PUBLIC = 1;

    /**
     * comment
     */
    public function foo(int $a): string
    {
        // comment
        return \sprintf('0x%02x', $a);
    }


}

$a = new namespace\A();
echo "public{$a->foo(77)}";
?></div>
PHP;

    /** @var class-string<PhpToken|\PhpToken> */
    protected static string $Token;

    /**
     * @dataProvider getTokenNameProvider
     *
     * @param array<string|null> $expected
     * @param array<PhpToken|\PhpToken> $input
     */
    public function testGetTokenName(array $expected, array $input): void
    {
        foreach ($input as $token) {
            $actual[] = $token->getTokenName();
        }

        $actualCode = Get::code($actual ?? []);
        $this->assertSame(
            $expected,
            $actual ?? [],
            'If $input changed, replace $expected with: ' . $actualCode,
        );
    }

    /**
     * @return array<array{array<string|null>,array<PhpToken|\PhpToken>}>
     */
    public static function getTokenNameProvider(): array
    {
        return [
            [
                [
                    'T_INLINE_HTML',
                    'T_OPEN_TAG',
                    'T_NAMESPACE',
                    'T_WHITESPACE',
                    'T_NAME_QUALIFIED',
                    ';',
                    'T_WHITESPACE',
                    'T_USE',
                    'T_WHITESPACE',
                    'T_STRING',
                    'T_NS_SEPARATOR',
                    '{',
                    'T_STRING',
                    'T_WHITESPACE',
                    'T_AS',
                    'T_WHITESPACE',
                    'T_STRING',
                    ',',
                    'T_WHITESPACE',
                    'T_STRING',
                    'T_WHITESPACE',
                    'T_AS',
                    'T_WHITESPACE',
                    'T_STRING',
                    '}',
                    ';',
                    'T_WHITESPACE',
                    'T_CLASS',
                    'T_WHITESPACE',
                    'T_STRING',
                    'T_WHITESPACE',
                    '{',
                    'T_WHITESPACE',
                    'T_CONST',
                    'T_WHITESPACE',
                    'T_STRING',
                    'T_WHITESPACE',
                    '=',
                    'T_WHITESPACE',
                    'T_LNUMBER',
                    ';',
                    'T_WHITESPACE',
                    'T_DOC_COMMENT',
                    'T_WHITESPACE',
                    'T_PUBLIC',
                    'T_WHITESPACE',
                    'T_FUNCTION',
                    'T_WHITESPACE',
                    'T_STRING',
                    '(',
                    'T_STRING',
                    'T_WHITESPACE',
                    'T_VARIABLE',
                    ')',
                    ':',
                    'T_WHITESPACE',
                    'T_STRING',
                    'T_WHITESPACE',
                    '{',
                    'T_WHITESPACE',
                    'T_COMMENT',
                    'T_WHITESPACE',
                    'T_RETURN',
                    'T_WHITESPACE',
                    'T_NAME_FULLY_QUALIFIED',
                    '(',
                    'T_CONSTANT_ENCAPSED_STRING',
                    ',',
                    'T_WHITESPACE',
                    'T_VARIABLE',
                    ')',
                    ';',
                    'T_WHITESPACE',
                    '}',
                    'T_WHITESPACE',
                    '}',
                    'T_WHITESPACE',
                    'T_VARIABLE',
                    'T_WHITESPACE',
                    '=',
                    'T_WHITESPACE',
                    'T_NEW',
                    'T_WHITESPACE',
                    'T_NAME_RELATIVE',
                    '(',
                    ')',
                    ';',
                    'T_WHITESPACE',
                    'T_ECHO',
                    'T_WHITESPACE',
                    '"',
                    'T_ENCAPSED_AND_WHITESPACE',
                    'T_CURLY_OPEN',
                    'T_VARIABLE',
                    'T_OBJECT_OPERATOR',
                    'T_STRING',
                    '(',
                    'T_LNUMBER',
                    ')',
                    '}',
                    '"',
                    ';',
                    'T_WHITESPACE',
                    'T_CLOSE_TAG',
                    'T_INLINE_HTML',
                ],
                static::$Token::tokenize(self::CODE, \TOKEN_PARSE),
            ],
            [
                [
                    null,
                ],
                [
                    new static::$Token(max(
                        10001,
                        \T_NAME_FULLY_QUALIFIED,
                        \T_NAME_RELATIVE,
                        \T_NAME_QUALIFIED,
                        \T_MATCH,
                        \T_READONLY,
                        \T_ENUM,
                        \T_PROPERTY_C,
                        \T_ATTRIBUTE,
                        \T_NULLSAFE_OBJECT_OPERATOR,
                        \T_AMPERSAND_FOLLOWED_BY_VAR_OR_VARARG,
                        \T_AMPERSAND_NOT_FOLLOWED_BY_VAR_OR_VARARG,
                    ) + 1, ''),
                ],
            ],
        ];
    }

    /**
     * @dataProvider isProvider
     *
     * @param bool[]|string $expected
     * @param array<PhpToken|\PhpToken> $input
     * @param int|string|array<int|string> $kind
     */
    public function testIs($expected, array $input, $kind): void
    {
        $this->maybeExpectException($expected);

        foreach ($input as $token) {
            $actual[] = $token->is($kind);
        }

        $actualCode = Get::code($actual ?? []);
        $this->assertSame(
            $expected,
            $actual ?? [],
            'If $input changed, replace $expected with: ' . $actualCode,
        );
    }

    /**
     * @return array<array{bool[]|string,array<PhpToken|\PhpToken>,mixed}>
     */
    public static function isProvider(): array
    {
        return [
            [
                [
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    true,
                    true,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    true,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    true,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    true,
                    true,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    true,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                ],
                static::$Token::tokenize(self::CODE, \TOKEN_PARSE),
                [
                    \T_WHITESPACE,
                    \T_COMMENT,
                    \T_DOC_COMMENT,
                    \T_OPEN_TAG,
                    '$a',
                ],
            ],
            [
                [
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                ],
                static::$Token::tokenize(self::CODE, \TOKEN_PARSE),
                \T_CONST,
            ],
            [
                [
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                ],
                static::$Token::tokenize(self::CODE, \TOKEN_PARSE),
                '$a',
            ],
            [
                TypeError::class,
                static::$Token::tokenize(self::CODE, \TOKEN_PARSE),
                false,
            ],
            [
                TypeError::class,
                static::$Token::tokenize(self::CODE, \TOKEN_PARSE),
                [
                    \T_OPEN_TAG,
                    '$a',
                    false,
                ],
            ],
            [
                TypeError::class,
                [
                    new static::$Token(\T_OPEN_TAG, "<?php\n"),
                    new static::$Token(\T_VARIABLE, '$a'),
                ],
                [
                    false,
                    \T_OPEN_TAG,
                    '$a',
                ],
            ],
            [
                [
                    true,
                    true,
                ],
                [
                    new static::$Token(\T_OPEN_TAG, "<?php\n"),
                    new static::$Token(\T_VARIABLE, '$a'),
                ],
                [
                    \T_OPEN_TAG,
                    '$a',
                    false,
                ],
            ],
        ];
    }

    /**
     * @dataProvider isIgnorableProvider
     *
     * @param bool[] $expected
     * @param array<PhpToken|\PhpToken> $input
     */
    public function testIsIgnorable(array $expected, array $input): void
    {
        foreach ($input as $token) {
            $actual[] = $token->isIgnorable();
        }

        $actualCode = Get::code($actual ?? []);
        $this->assertSame(
            $expected,
            $actual ?? [],
            'If $input changed, replace $expected with: ' . $actualCode,
        );
    }

    /**
     * @return array<array{bool[],array<PhpToken|\PhpToken>}>
     */
    public static function isIgnorableProvider(): array
    {
        return [
            [
                [
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    true,
                    true,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    true,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                ],
                static::$Token::tokenize(self::CODE, \TOKEN_PARSE),
            ],
        ];
    }

    public function testToString(): void
    {
        $code = '';
        foreach (static::$Token::tokenize(self::CODE, \TOKEN_PARSE) as $token) {
            $code .= (string) $token;
        }
        $this->assertSame(self::CODE, $code);
    }

    /**
     * @dataProvider tokenizeProvider
     *
     * @param array<PhpToken|\PhpToken> $expected
     */
    public function testTokenize(array $expected, string $input, int $flags = 0): void
    {
        $actual = static::$Token::tokenize(Str::setEol($input), $flags);

        $actualCode = array_reduce(
            $actual,
            fn($code, $token) => $code . sprintf(
                "    new static::\$Token(%s, %s, %d, %d),\n",
                $token->id < 256 ? $token->id : '\\' . $token->getTokenName(),
                Get::code($token->text),
                $token->line,
                $token->pos,
            ),
            "[\n"
        ) . ']';
        $this->assertEquals(
            $expected,
            $actual,
            'If $input changed, replace $expected with: ' . $actualCode,
        );
    }

    /**
     * @return array<array{array<PhpToken|\PhpToken>,string,2?:int}>
     */
    public static function tokenizeProvider(): array
    {
        return [
            'with TOKEN_PARSE' => [
                [
                    new static::$Token(\T_INLINE_HTML, '<div>', 1, 0),
                    new static::$Token(\T_OPEN_TAG, "<?php\n", 1, 5),
                    new static::$Token(\T_NAMESPACE, 'namespace', 2, 11),
                    new static::$Token(\T_WHITESPACE, ' ', 2, 20),
                    new static::$Token(\T_NAME_QUALIFIED, 'Foo\Bar', 2, 21),
                    new static::$Token(59, ';', 2, 28),
                    new static::$Token(\T_WHITESPACE, "\n\n", 2, 29),
                    new static::$Token(\T_USE, 'use', 4, 31),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 34),
                    new static::$Token(\T_STRING, 'Foo', 4, 35),
                    new static::$Token(\T_NS_SEPARATOR, '\\', 4, 38),
                    new static::$Token(123, '{', 4, 39),
                    new static::$Token(\T_STRING, 'A', 4, 40),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 41),
                    new static::$Token(\T_AS, 'as', 4, 42),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 44),
                    new static::$Token(\T_STRING, 'AA', 4, 45),
                    new static::$Token(44, ',', 4, 47),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 48),
                    new static::$Token(\T_STRING, 'B', 4, 49),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 50),
                    new static::$Token(\T_AS, 'AS', 4, 51),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 53),
                    new static::$Token(\T_STRING, 'BB', 4, 54),
                    new static::$Token(125, '}', 4, 56),
                    new static::$Token(59, ';', 4, 57),
                    new static::$Token(\T_WHITESPACE, "\n\n", 4, 58),
                    new static::$Token(\T_CLASS, 'class', 6, 60),
                    new static::$Token(\T_WHITESPACE, ' ', 6, 65),
                    new static::$Token(\T_STRING, 'A', 6, 66),
                    new static::$Token(\T_WHITESPACE, "\n", 6, 67),
                    new static::$Token(123, '{', 7, 68),
                    new static::$Token(\T_WHITESPACE, "\n    ", 7, 69),
                    new static::$Token(\T_CONST, 'const', 8, 74),
                    new static::$Token(\T_WHITESPACE, ' ', 8, 79),
                    new static::$Token(\T_STRING, 'PUBLIC', 8, 80),
                    new static::$Token(\T_WHITESPACE, ' ', 8, 86),
                    new static::$Token(61, '=', 8, 87),
                    new static::$Token(\T_WHITESPACE, ' ', 8, 88),
                    new static::$Token(\T_LNUMBER, '1', 8, 89),
                    new static::$Token(59, ';', 8, 90),
                    new static::$Token(\T_WHITESPACE, "\n\n    ", 8, 91),
                    new static::$Token(\T_DOC_COMMENT, "/**\n     * comment\n     */", 10, 97),
                    new static::$Token(\T_WHITESPACE, "\n    ", 12, 123),
                    new static::$Token(\T_PUBLIC, 'public', 13, 128),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 134),
                    new static::$Token(\T_FUNCTION, 'function', 13, 135),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 143),
                    new static::$Token(\T_STRING, 'foo', 13, 144),
                    new static::$Token(40, '(', 13, 147),
                    new static::$Token(\T_STRING, 'int', 13, 148),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 151),
                    new static::$Token(\T_VARIABLE, '$a', 13, 152),
                    new static::$Token(41, ')', 13, 154),
                    new static::$Token(58, ':', 13, 155),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 156),
                    new static::$Token(\T_STRING, 'string', 13, 157),
                    new static::$Token(\T_WHITESPACE, "\n    ", 13, 163),
                    new static::$Token(123, '{', 14, 168),
                    new static::$Token(\T_WHITESPACE, "\n        ", 14, 169),
                    new static::$Token(\T_COMMENT, '// comment', 15, 178),
                    new static::$Token(\T_WHITESPACE, "\n        ", 15, 188),
                    new static::$Token(\T_RETURN, 'return', 16, 197),
                    new static::$Token(\T_WHITESPACE, ' ', 16, 203),
                    new static::$Token(\T_NAME_FULLY_QUALIFIED, '\sprintf', 16, 204),
                    new static::$Token(40, '(', 16, 212),
                    new static::$Token(\T_CONSTANT_ENCAPSED_STRING, "'0x%02x'", 16, 213),
                    new static::$Token(44, ',', 16, 221),
                    new static::$Token(\T_WHITESPACE, ' ', 16, 222),
                    new static::$Token(\T_VARIABLE, '$a', 16, 223),
                    new static::$Token(41, ')', 16, 225),
                    new static::$Token(59, ';', 16, 226),
                    new static::$Token(\T_WHITESPACE, "\n    ", 16, 227),
                    new static::$Token(125, '}', 17, 232),
                    new static::$Token(\T_WHITESPACE, "\n\n\n", 17, 233),
                    new static::$Token(125, '}', 20, 236),
                    new static::$Token(\T_WHITESPACE, "\n\n", 20, 237),
                    new static::$Token(\T_VARIABLE, '$a', 22, 239),
                    new static::$Token(\T_WHITESPACE, ' ', 22, 241),
                    new static::$Token(61, '=', 22, 242),
                    new static::$Token(\T_WHITESPACE, ' ', 22, 243),
                    new static::$Token(\T_NEW, 'new', 22, 244),
                    new static::$Token(\T_WHITESPACE, ' ', 22, 247),
                    new static::$Token(\T_NAME_RELATIVE, 'namespace\A', 22, 248),
                    new static::$Token(40, '(', 22, 259),
                    new static::$Token(41, ')', 22, 260),
                    new static::$Token(59, ';', 22, 261),
                    new static::$Token(\T_WHITESPACE, "\n", 22, 262),
                    new static::$Token(\T_ECHO, 'echo', 23, 263),
                    new static::$Token(\T_WHITESPACE, ' ', 23, 267),
                    new static::$Token(34, '"', 23, 268),
                    new static::$Token(\T_ENCAPSED_AND_WHITESPACE, 'public', 23, 269),
                    new static::$Token(\T_CURLY_OPEN, '{', 23, 275),
                    new static::$Token(\T_VARIABLE, '$a', 23, 276),
                    new static::$Token(\T_OBJECT_OPERATOR, '->', 23, 278),
                    new static::$Token(\T_STRING, 'foo', 23, 280),
                    new static::$Token(40, '(', 23, 283),
                    new static::$Token(\T_LNUMBER, '77', 23, 284),
                    new static::$Token(41, ')', 23, 286),
                    new static::$Token(125, '}', 23, 287),
                    new static::$Token(34, '"', 23, 288),
                    new static::$Token(59, ';', 23, 289),
                    new static::$Token(\T_WHITESPACE, "\n", 23, 290),
                    new static::$Token(\T_CLOSE_TAG, '?>', 24, 291),
                    new static::$Token(\T_INLINE_HTML, '</div>', 24, 293),
                ],
                self::CODE,
                \TOKEN_PARSE,
            ],
            'without TOKEN_PARSE' => [
                [
                    new static::$Token(\T_INLINE_HTML, '<div>', 1, 0),
                    new static::$Token(\T_OPEN_TAG, "<?php\n", 1, 5),
                    new static::$Token(\T_NAMESPACE, 'namespace', 2, 11),
                    new static::$Token(\T_WHITESPACE, ' ', 2, 20),
                    new static::$Token(\T_NAME_QUALIFIED, 'Foo\Bar', 2, 21),
                    new static::$Token(59, ';', 2, 28),
                    new static::$Token(\T_WHITESPACE, "\n\n", 2, 29),
                    new static::$Token(\T_USE, 'use', 4, 31),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 34),
                    new static::$Token(\T_STRING, 'Foo', 4, 35),
                    new static::$Token(\T_NS_SEPARATOR, '\\', 4, 38),
                    new static::$Token(123, '{', 4, 39),
                    new static::$Token(\T_STRING, 'A', 4, 40),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 41),
                    new static::$Token(\T_AS, 'as', 4, 42),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 44),
                    new static::$Token(\T_STRING, 'AA', 4, 45),
                    new static::$Token(44, ',', 4, 47),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 48),
                    new static::$Token(\T_STRING, 'B', 4, 49),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 50),
                    new static::$Token(\T_AS, 'AS', 4, 51),
                    new static::$Token(\T_WHITESPACE, ' ', 4, 53),
                    new static::$Token(\T_STRING, 'BB', 4, 54),
                    new static::$Token(125, '}', 4, 56),
                    new static::$Token(59, ';', 4, 57),
                    new static::$Token(\T_WHITESPACE, "\n\n", 4, 58),
                    new static::$Token(\T_CLASS, 'class', 6, 60),
                    new static::$Token(\T_WHITESPACE, ' ', 6, 65),
                    new static::$Token(\T_STRING, 'A', 6, 66),
                    new static::$Token(\T_WHITESPACE, "\n", 6, 67),
                    new static::$Token(123, '{', 7, 68),
                    new static::$Token(\T_WHITESPACE, "\n    ", 7, 69),
                    new static::$Token(\T_CONST, 'const', 8, 74),
                    new static::$Token(\T_WHITESPACE, ' ', 8, 79),
                    new static::$Token(\T_PUBLIC, 'PUBLIC', 8, 80),
                    new static::$Token(\T_WHITESPACE, ' ', 8, 86),
                    new static::$Token(61, '=', 8, 87),
                    new static::$Token(\T_WHITESPACE, ' ', 8, 88),
                    new static::$Token(\T_LNUMBER, '1', 8, 89),
                    new static::$Token(59, ';', 8, 90),
                    new static::$Token(\T_WHITESPACE, "\n\n    ", 8, 91),
                    new static::$Token(\T_DOC_COMMENT, "/**\n     * comment\n     */", 10, 97),
                    new static::$Token(\T_WHITESPACE, "\n    ", 12, 123),
                    new static::$Token(\T_PUBLIC, 'public', 13, 128),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 134),
                    new static::$Token(\T_FUNCTION, 'function', 13, 135),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 143),
                    new static::$Token(\T_STRING, 'foo', 13, 144),
                    new static::$Token(40, '(', 13, 147),
                    new static::$Token(\T_STRING, 'int', 13, 148),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 151),
                    new static::$Token(\T_VARIABLE, '$a', 13, 152),
                    new static::$Token(41, ')', 13, 154),
                    new static::$Token(58, ':', 13, 155),
                    new static::$Token(\T_WHITESPACE, ' ', 13, 156),
                    new static::$Token(\T_STRING, 'string', 13, 157),
                    new static::$Token(\T_WHITESPACE, "\n    ", 13, 163),
                    new static::$Token(123, '{', 14, 168),
                    new static::$Token(\T_WHITESPACE, "\n        ", 14, 169),
                    new static::$Token(\T_COMMENT, '// comment', 15, 178),
                    new static::$Token(\T_WHITESPACE, "\n        ", 15, 188),
                    new static::$Token(\T_RETURN, 'return', 16, 197),
                    new static::$Token(\T_WHITESPACE, ' ', 16, 203),
                    new static::$Token(\T_NAME_FULLY_QUALIFIED, '\sprintf', 16, 204),
                    new static::$Token(40, '(', 16, 212),
                    new static::$Token(\T_CONSTANT_ENCAPSED_STRING, "'0x%02x'", 16, 213),
                    new static::$Token(44, ',', 16, 221),
                    new static::$Token(\T_WHITESPACE, ' ', 16, 222),
                    new static::$Token(\T_VARIABLE, '$a', 16, 223),
                    new static::$Token(41, ')', 16, 225),
                    new static::$Token(59, ';', 16, 226),
                    new static::$Token(\T_WHITESPACE, "\n    ", 16, 227),
                    new static::$Token(125, '}', 17, 232),
                    new static::$Token(\T_WHITESPACE, "\n\n\n", 17, 233),
                    new static::$Token(125, '}', 20, 236),
                    new static::$Token(\T_WHITESPACE, "\n\n", 20, 237),
                    new static::$Token(\T_VARIABLE, '$a', 22, 239),
                    new static::$Token(\T_WHITESPACE, ' ', 22, 241),
                    new static::$Token(61, '=', 22, 242),
                    new static::$Token(\T_WHITESPACE, ' ', 22, 243),
                    new static::$Token(\T_NEW, 'new', 22, 244),
                    new static::$Token(\T_WHITESPACE, ' ', 22, 247),
                    new static::$Token(\T_NAME_RELATIVE, 'namespace\A', 22, 248),
                    new static::$Token(40, '(', 22, 259),
                    new static::$Token(41, ')', 22, 260),
                    new static::$Token(59, ';', 22, 261),
                    new static::$Token(\T_WHITESPACE, "\n", 22, 262),
                    new static::$Token(\T_ECHO, 'echo', 23, 263),
                    new static::$Token(\T_WHITESPACE, ' ', 23, 267),
                    new static::$Token(34, '"', 23, 268),
                    new static::$Token(\T_ENCAPSED_AND_WHITESPACE, 'public', 23, 269),
                    new static::$Token(\T_CURLY_OPEN, '{', 23, 275),
                    new static::$Token(\T_VARIABLE, '$a', 23, 276),
                    new static::$Token(\T_OBJECT_OPERATOR, '->', 23, 278),
                    new static::$Token(\T_STRING, 'foo', 23, 280),
                    new static::$Token(40, '(', 23, 283),
                    new static::$Token(\T_LNUMBER, '77', 23, 284),
                    new static::$Token(41, ')', 23, 286),
                    new static::$Token(125, '}', 23, 287),
                    new static::$Token(34, '"', 23, 288),
                    new static::$Token(59, ';', 23, 289),
                    new static::$Token(\T_WHITESPACE, "\n", 23, 290),
                    new static::$Token(\T_CLOSE_TAG, '?>', 24, 291),
                    new static::$Token(\T_INLINE_HTML, '</div>', 24, 293),
                ],
                self::CODE,
            ],
        ];
    }
}
