#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\App;
use Lkrms\Store\Cache;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

App::load(__DIR__)->enableCache();

print_r([
    'App::getInstance()->CachePath' => App::getInstance()->CachePath,
    'App::get("DataPath")'          => App::get("DataPath"),
    'App::get("LogPath")'           => App::get("LogPath"),
    'Cache::getInstance()'          => Cache::getInstance(),
]);
