#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Err\Err;
use Lkrms\Store\Cache;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

Err::handleErrors();

Cache::load();

Cache::set('key', 'value1');
print_r(Cache::get('key'));

Cache::set('key', ['value1', 'value2']);
print_r(Cache::get('key'));

print_r(Cache::maybeGet(
    [basename(__FILE__), "MaybeGet"],
    function ()
    {
        return [
            "key1" => "value1",
            "key2" => "value2",
        ];
    }, 2
));

foreach ([1, 2] as $seconds)
{
    sleep($seconds);
    print_r(Cache::maybeGet(
        [basename(__FILE__), "MaybeGet"],
        "time",
        2
    ));
}
