#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Cache;
use Lkrms\Err;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

Err::HandleErrors();

Cache::Load();

Cache::Set('key', 'value1');
var_dump(Cache::Get('key'));

Cache::Set('key', ['value1', 'value2']);
var_dump(Cache::Get('key'));

var_dump(Cache::MaybeGet(
    [basename(__FILE__), "MaybeGet"],
    function ()
    {
        return [
            "key1" => "value1",
            "key2" => "value2",
        ];
    }, 2
));

foreach ([1, 2] as $seconds)
{
    sleep($seconds);
    var_dump(Cache::MaybeGet(
        [basename(__FILE__), "MaybeGet"],
        "time"
    ));
}

