#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Console\Console;
use Lkrms\Console\ConsoleTarget\Stream;
use Lkrms\Err;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

Err::handleErrors();

// Send all output, including debug messages and errors, to STDOUT
Console::addTarget(new Stream(STDOUT));

// Disable output logging
Console::disableDefaultLogTarget();

$items = [
    [100, 101, 102],
    [200, 201, 202],
    [300, 301, 302],
];

Console::group("Processing items");

for ($i = 0; $i < count($items); $i++)
{
    Console::info("Processing row:", $i + 1);

    for ($j = 0; $j < count($items[$i]); $j++)
    {
        Console::log("Processing item:", $items[$i][$j]);
    }

    if ($i % 2)
    {
        Console::warn("WARNING: odd-numbered index at row:", ($i + 1));
    }
    else
    {
        Console::debug("Row processing complete");
    }
}

Console::groupEnd();

$i = 0;

while ($i++ < 5)
{
    Console::infoOnce("This message is printed repeatedly",
        "but it should only appear once");
    Console::logOnce("This message is printed repeatedly",
        "but it should only appear once");
    Console::debugOnce("This message is printed repeatedly",
        "but it should only appear once");
}

