#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Convert;
use Lkrms\Err;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

Err::HandleErrors();

$data = [
    "user_id"       => 7654,
    "fields"        => [
        "surname"   => "Williams",
        "email"     => "JWilliams432@gmail.com",
        "notify_by" => [
            "email",
            "sms",
        ],
    ],
];

$queries = [
    "no_force_numeric_keys" => Convert::HttpBuildQuery($data),
    "force_numeric_keys"    => Convert::HttpBuildQuery($data, true),
];

$decoded = array_map(
    function ($q)
    {
        return urldecode($q);
    }, $queries
);

var_dump([$queries, $decoded]);

$identifiers = [
    "twowords", "TWOWORDS", "twoWords", "TwoWords",
    "two_words", "TWO_WORDS", "two_Words", "Two_Words",
    "two-words", "TWO-WORDS", "Two-Words",
];

$identifiers = array_combine($identifiers, array_map(function ($i)
{
    return Convert::IdentifierToSnakeCase($i);
}, $identifiers));

var_dump($identifiers);
