#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Convert;
use Lkrms\Err;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

Err::HandleErrors();

$data = [
    "user_id"       => 7654,
    "fields"        => [
        "surname"   => "Williams",
        "email"     => "JWilliams432@gmail.com",
        "notify_by" => [
            "email",
            "sms",
        ],
    ],
];

$queries = [
    "no_force_numeric_keys" => Convert::dataToQuery($data),
    "force_numeric_keys"    => Convert::dataToQuery($data, true),
];

$decoded = array_map(
    function ($q)
    {
        return urldecode($q);
    }, $queries
);

print_r([$queries, $decoded]);

$identifiers = [
    "twowords", "TWOWORDS", "twoWords", "TwoWords",
    "two_words", "TWO_WORDS", "two_Words", "Two_Words",
    "two-words", "TWO-WORDS", "Two-Words",
];

$snakeCase = array_combine($identifiers, array_map(function ($i)
{
    return Convert::toSnakeCase($i);
}, $identifiers));

print_r($snakeCase);

$kebabCase = array_combine($identifiers, array_map(function ($i)
{
    return Convert::toKebabCase($i);
}, $identifiers));

print_r($kebabCase);

$list = [
    ['id' => 38, 'name' => 'Amir'],
    ['id' => 32, 'name' => 'Greta'],
    ['id' => 71, 'name' => 'Terry'],
];

$map = Convert::listToMap($list, 'id');

print_r($map);
