#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Facade\Err;
use UnexpectedValueException;

require __DIR__ . '/../vendor/autoload.php';

Err::register();
Err::silencePath(__DIR__ . '/../vendor/adodb/adodb-php');

throw new UnexpectedValueException('Well, this was unexpected');
