#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Err\Err;
use UnexpectedValueException;

require __DIR__ . '/../vendor/autoload.php';

Err::load();
Err::silencePaths(__DIR__ . '/../vendor/adodb/adodb-php');

throw new UnexpectedValueException('Well, this was unexpected');
