#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Facade\Err;
use Lkrms\Utility\File;
use Lkrms\Utility\Test;

require __DIR__ . '/../vendor/autoload.php';

Err::register();

$file = fopen(__FILE__, 'r');
$url = fopen('https://1.1.1.1/', 'r');

$compare = [
    [
        realpath(__FILE__),
        __DIR__ . '/../' . basename(__DIR__) . '/' . basename(__FILE__),
    ],
    [
        realpath(__FILE__),
        __DIR__ . '/../' . basename(__DIR__),
    ],
];

print_r([
    '__FILE__' => File::getStreamUri($file),
    '1.1.1.1' => File::getStreamUri($url),
    'STDIN' => File::getStreamUri(STDIN),
    'STDOUT' => File::getStreamUri(STDOUT),
    'STDERR' => File::getStreamUri(STDERR),
    'areSame' => array_map(
        function ($f) { return array_merge($f, [Test::areSameFile($f[0], $f[1])]); },
        $compare
    )
]);
