#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Err;
use Lkrms\Generate;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

Err::HandleErrors();

$distances = [
    "DELIVERY,milk delivery,false"  => Generate::textDistance("DELIVERY", "milk delivery", false),
    "DELIVERY,milk deliverer"       => Generate::textDistance("DELIVERY", "milk deliverer"),
    "DELIVERY,milk delivery"        => Generate::textDistance("DELIVERY", "milk delivery"),
    "DELIVERY - MILK,milk delivery" => Generate::textDistance("DELIVERY - MILK", "milk delivery"),
    "DELIVERY,delivery"             => Generate::textDistance("DELIVERY", "delivery"),
];

print_r($distances);

$similarities = [
    "DELIVERY,milk delivery,false"  => Generate::textSimilarity("DELIVERY", "milk delivery", false),
    "DELIVERY,milk deliverer"       => Generate::textSimilarity("DELIVERY", "milk deliverer"),
    "DELIVERY,milk delivery"        => Generate::textSimilarity("DELIVERY", "milk delivery"),
    "DELIVERY - MILK,milk delivery" => Generate::textSimilarity("DELIVERY - MILK", "milk delivery"),
    "DELIVERY,delivery"             => Generate::textSimilarity("DELIVERY", "delivery"),
];

print_r($similarities);
