#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Concern\TBindable;
use Lkrms\Contract\IBindable;
use Lkrms\Err\Err;
use Lkrms\Facade\DI;
use UnexpectedValueException;

$loader = require (__DIR__ . "/../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__);

Err::load();

class IdGenerator
{
    private $counters = [];

    public function getNext(string $type)
    {
        $this->counters[$type] = $this->counters[$type] ?? 100 * (count($this->counters) + 1);

        return $this->counters[$type]++;
    }
}

class User
{
    public $id;

    public function __construct(IdGenerator $idGenerator)
    {
        $this->id = $idGenerator->getNext(__CLASS__);
    }
}

class Staff extends User
{
    public $staffId;

    public function __construct(IdGenerator $idGenerator)
    {
        parent::__construct($idGenerator);
        $this->staffId = $idGenerator->getNext(__CLASS__);
    }
}

class DepartmentHead extends Staff
{
    public $department;

    public function __construct(IdGenerator $idGenerator, Department $department)
    {
        parent::__construct($idGenerator);
        $this->department = $department;
    }
}

class Department
{
    public $id;

    public $name;

    public function __construct(IdGenerator $idGenerator, $name = null)
    {
        $this->id   = $idGenerator->getNext(__CLASS__);
        $this->name = $name;
    }
}

class DepartmentStaff implements IBindable
{
    use TBindable;

    public $user;

    public $department;

    public $departmentHead;

    // Parameter order is a workaround for
    // https://github.com/Level-2/Dice/issues/200
    public function __construct(User $user, DepartmentHead $departmentHead, Department $department)
    {
        $this->user           = $user;
        $this->department     = $department;
        $this->departmentHead = $departmentHead;
    }

    public static function getBindings(): array
    {
        // Create 'Staff' instead of 'User' instances when creating 'DepartmentStaff'
        return [User::class => Staff::class];
    }
}

$exceptions = [];

DI::singleton(IdGenerator::class);

// Create one 'Department' per 'DepartmentStaff'
DI::bind(DepartmentStaff::class, null, null, [Department::class]);

// Register 'DepartmentStaff' bindings
DI::service(DepartmentStaff::class);

// Give 'Department' instances a default name
DI::bind(Department::class, null, ["<auto>"]);

try
{
    // Should throw an exception for trying to substitute a 'shareInstances'
    // dependency
    DI::bind(DepartmentStaff::class, null, null, null, [
        "substitutions" => [Department::class => "SpecialDepartment"],
    ]);
}
catch (UnexpectedValueException $ex)
{
    $exceptions[] = $ex;
}

// $user1 should be a 'User' instance
$user1 = DI::get(User::class);

// $user2 should be a 'Staff' instance
$user2 = DI::inContextOf(DepartmentStaff::class)->get(User::class);

// $user3 should be a 'User' instance
$user3 = DI::get(User::class);

// User, Staff and Department IDs should all increment
$exec1 = DI::get(DepartmentHead::class);
$exec2 = DI::get(DepartmentHead::class);

// Department names should be applied to separate instances
$dept1 = DI::get(Department::class, "English");
$dept2 = DI::get(Department::class, "Mathematics");

// One department instance should be created per object tree
$deptStaff1 = DI::get(DepartmentStaff::class);
$deptStaff2 = DI::get(DepartmentStaff::class);

print_r([
    "exceptions"  => $exceptions,
    "idGenerator" => DI::get(IdGenerator::class),
    "user1"       => $user1,
    "user2"       => $user2,
    "user3"       => $user3,
    "exec1"       => $exec1,
    "exec2"       => $exec2,
    "dept1"       => $dept1,
    "dept2"       => $dept2,
    "deptStaff1"  => $deptStaff1,
    "deptStaff2"  => $deptStaff2,
]);
