#!/usr/bin/env php
<?php

namespace Lkrms\Tests;

use Lkrms\Utility\Env;

require __DIR__ . '/../vendor/autoload.php';

Env::set('app_base_path', __DIR__);

require __DIR__ . '/../lib/lk-util/bootstrap.php';
