#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Curler;

use Lkrms\Curler\Curler;
use Lkrms\Env;
use Lkrms\Err\Err;

$loader = require (__DIR__ . "/../../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__ . "/..");

Err::handleErrors();

Env::load(__DIR__ . "/../.env");

class A
{
    public function __construct()
    {
        $curl = new Curler("https://api.github.com/meta");
        $curl->enableDebug();
        print_r($curl->get());
        print_r($curl->getJson());
    }
}

new A();
