#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Mixin;

use Lkrms\Err;
use Lkrms\Mixin\IExtensible;
use Lkrms\Mixin\TConstructible;
use Lkrms\Mixin\TExtensible;

$loader = require (__DIR__ . "/../../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__ . "/..");

Err::HandleErrors();

class A implements IExtensible
{
    use TConstructible, TExtensible;

    public $Id;

    public $Name;
}

class B extends A
{
    public $Data = [];
}

$a = A::From([
    "id"    => 1,
    "name"  => "Test entry",
    "DATA"  => [3, 4, 5],
    "DATA2" => [32, 42, 52],
]);
$b = B::From([
    "id"   => 2,
    "name" => "Another test entry",
    "DATA" => [13, 14, 15],
]);

$a_id   = $a->Id;
$a_name = $a->Name;
$a_data = $a->Data;
$a_meta = $a->GetMetaProperties();

$b_id   = $b->Id;
$b_name = $b->Name;
$b_data = $b->Data;

print_r([
    'a_set' => $a,
    'b_set' => $b,
    'a_get' => ['id' => $a_id, 'name' => $a_name, 'data' => $a_data, 'meta' => $a_meta],
    'b_get' => ['id' => $b_id, 'name' => $b_name, 'data' => $b_data],
]);
