#!/usr/bin/env php
<?php declare(strict_types=1);

use Composer\Autoload\ClassLoader;
use Salient\Cli\CliApplication;
use Salient\Sli\Command\Generate\GenerateBuilder;
use Salient\Sli\Command\Generate\GenerateFacade;
use Salient\Sli\Command\Generate\GenerateSyncEntity;
use Salient\Sli\Command\Generate\GenerateSyncProvider;
use Salient\Sli\Command\Generate\GenerateTests;
use Salient\Sli\Command\AnalyseClass;
use Salient\Sync\Command\CheckSyncProviderHeartbeat;
use Salient\Sync\Command\GetSyncEntity;
use Salient\Sync\Command\SendHttpSyncProviderRequest;

/** @var ClassLoader */
$loader = require $_composer_autoload_path
    ?? dirname(__DIR__, 3) . '/vendor/autoload.php';

(new CliApplication())
    ->command(['generate', 'builder'], GenerateBuilder::class)
    ->command(['generate', 'facade'], GenerateFacade::class)
    ->command(['generate', 'tests'], GenerateTests::class)
    ->command(['generate', 'sync', 'entity'], GenerateSyncEntity::class)
    ->command(['generate', 'sync', 'provider'], GenerateSyncProvider::class)
    ->command(['sync', 'check-heartbeat'], CheckSyncProviderHeartbeat::class)
    ->command(['sync', 'get-entity'], GetSyncEntity::class)
    ->command(['sync', 'http', 'head'], SendHttpSyncProviderRequest::class)
    ->command(['sync', 'http', 'get'], SendHttpSyncProviderRequest::class)
    ->command(['sync', 'http', 'post'], SendHttpSyncProviderRequest::class)
    ->command(['sync', 'http', 'put'], SendHttpSyncProviderRequest::class)
    ->command(['sync', 'http', 'delete'], SendHttpSyncProviderRequest::class)
    ->command(['sync', 'http', 'patch'], SendHttpSyncProviderRequest::class)
    ->command(['analyse'], AnalyseClass::class)
    ->resumeCache()
    ->logOutput()
    ->runAndExit();
