#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Support;

use Salient\Core\Facade\Console;
use Salient\Core\Facade\Err;
use Salient\Http\HttpResponse;
use Salient\Http\HttpServer;
use Salient\Http\HttpServerRequest;

require __DIR__ . '/../../../vendor/autoload.php';

Err::register();

$server = new HttpServer('localhost', 8306);
$server->start();
$baseUrl = $server->getBaseUri();
Console::log('Listening at:', implode("\n", [$baseUrl, "$baseUrl/loop", "$baseUrl/return"]));
$lastClient = $server->listen(
    function (HttpServerRequest $request, bool &$continue, &$return): HttpResponse {
        Console::log($request->getMethod() . ' request from ' . $request->getServerParams()['REMOTE_ADDR'] . ':', $request->getRequestTarget());
        switch ($request->getRequestTarget()) {
            case '/loop':
                $continue = true;
                break;
            case '/return':
                $return = $request->getServerParams()['REMOTE_ADDR'];
                break;
        }

        return new HttpResponse(200, null, "Called with:\n" . print_r($request, true));
    }
);
$server->stop();
Console::log('Last client:', $lastClient ?: '<not returned>');
