#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Support;

use My\Full\Classname as Another;
use My\Full\Classname as AnotherClass, My\Full\Classname;
use My\Full\NSname;
use Salient\Core\Facade\Err;
use Salient\Sli\Support\TokenExtractor;
use some\namespace\{ClassA, ClassB, ClassC as C, special\ClassD as D};
use ArrayObject;

use function My\Full\functionName;
use function My\Full\functionName as func;
use function some\namespace\{fn_a, fn_b, fn_c};

use const My\Full\CONSTANT;
use const some\namespace\{ConstA, ConstB, ConstC};

require __DIR__ . '/../../vendor/autoload.php';

Err::register();

$extractor = new TokenExtractor(__FILE__);
print_r($extractor->getUseMap());
