#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Support;

use Lkrms\Err\Err;
use Lkrms\Facade\Console;
use Lkrms\Support\Http\HttpRequest;
use Lkrms\Support\Http\HttpResponse;
use Lkrms\Support\Http\HttpServer;

$loader = require __DIR__ . '/../../vendor/autoload.php';
$loader->addPsr4('Lkrms\\Tests\\', dirname(__DIR__));

Err::load();

$server = new HttpServer('localhost', 8306);
$server->start();
Console::log('Listening at:', 'http://localhost:8306');
$server->listen(
    function (HttpRequest $request, bool &$continue, &$return): HttpResponse {
        $response = new HttpResponse("Called with:\n" . print_r($request, true));
        $continue = false;

        return $response;
    }
);
$server->stop();
