#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Support;

use Lkrms\Err\Err;
use Lkrms\Facade\Console;
use Lkrms\Support\Http\HttpRequest;
use Lkrms\Support\Http\HttpResponse;
use Lkrms\Support\Http\HttpServer;

require __DIR__ . '/../../vendor/autoload.php';

Err::load();

$server = new HttpServer('localhost', 8306);
$server->start();
$baseUrl = $server->getBaseUrl();
Console::log('Listening at:', implode("\n", [$baseUrl, "$baseUrl/loop", "$baseUrl/return"]));
$lastClient = $server->listen(
    function (HttpRequest $request, bool &$continue, &$return): HttpResponse {
        Console::log($request->Method . ' request from ' . $request->Client . ':', $request->Target);
        switch ($request->Target) {
            case '/loop':
                $continue = true;
                break;
            case '/return':
                $return = $request->Client;
                break;
        }

        return new HttpResponse("Called with:\n" . print_r($request, true));
    }
);
$server->stop();
Console::log('Last client:', $lastClient ?: '<not returned>');
