#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Support;

use ArrayObject;
use Lkrms\Err\Err;
use Lkrms\Support\TokenExtractor;
use My\Full\Classname as Another;
use My\Full\Classname as AnotherClass, My\Full\Classname;
use My\Full\NSname;
use some\namespace\{ClassA, ClassB, ClassC as C, special\ClassD as D};

use const My\Full\CONSTANT;
use const some\namespace\{ConstA, ConstB, ConstC};

use function My\Full\functionName;
use function My\Full\functionName as func;
use function some\namespace\{fn_a, fn_b, fn_c};

$loader = require __DIR__ . '/../../vendor/autoload.php';
$loader->addPsr4('Lkrms\\Tests\\', dirname(__DIR__));

Err::load();

$extractor = new TokenExtractor(__FILE__);
print_r($extractor->getUseMap());
