#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Template;

use Lkrms\Template\Singleton;

$loader = require (__DIR__ . "/../../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__ . "/..");

class A extends Singleton
{
}

class B extends A
{
}

class C extends A
{
    public $name;

    public static function GetInstance(string $name = null)
    {
        if (self::hasInstance())
        {
            return parent::getInstance();
        }

        $instance       = parent::getInstance();
        $instance->name = $name;

        return $instance;
    }
}

$a  = A::getInstance();
$aa = A::getInstance();

$b  = B::getInstance();
$bb = B::getInstance();

$c  = C::getInstance("name1");
$cc = C::getInstance("name2");

print_r([
    "a"      => $a,
    "b"      => $b,
    "c"      => $c,
    "a===aa" => $a === $aa,
    "b===bb" => $b === $bb,
    "c===cc" => $c === $cc,
    "a===b"  => $a === $b,
]);
