#!/usr/bin/env php
<?php

namespace Lkrms\Tests\Template;

use Lkrms\Contract\IExtensible;
use Lkrms\Contract\IReadable;
use Lkrms\Contract\IResolvable;
use Lkrms\Contract\IWritable;
use Lkrms\Concern\TConstructible;
use Lkrms\Concern\TExtensible;
use Lkrms\Concern\TReadable;
use Lkrms\Concern\TResolvable;
use Lkrms\Concern\TSettable;
use Lkrms\Err\Err;
use Throwable;
use UnexpectedValueException;

$loader = require (__DIR__ . "/../../vendor/autoload.php");
$loader->addPsr4("Lkrms\\Tests\\", __DIR__ . "/..");

Err::handleErrors();

class A implements IExtensible, IReadable, IWritable, IResolvable
{
    use TConstructible, TExtensible, TReadable, TSettable, TResolvable;

    public $Id;

    public $Name;
}

class B extends A
{
    public $Data = [];
}

$exceptions = [];

$value1 = [
    "id"    => 1,
    "name"  => "Test entry",
    "DATA"  => [3, 4, 5],
    "DATA2" => [32, 42, 52],
];

$value2 = [
    "id"   => 2,
    "name" => "Another test entry",
    "DATA" => [13, 14, 15],
];

$value3 = [
    "id"   => 3,
    "name" => "One more test entry",
    "DATA" => [29, 27, 26],
];

$a = A::from(null, $value1);
$b = B::from(null, $value2);
$c = B::from(null, $value3);
$d = iterator_to_array(B::listFrom(null, [$value1, $value2, $value3]));

try
{
    $e = B::listFrom(null, [$value1, $value2, $c]);
}
catch (UnexpectedValueException $ex)
{
    $exceptions[] = $ex;
}

$a_id   = $a->Id;
$a_name = $a->Name;
// @phpstan-ignore-next-line
$a_data = $a->Data;
$a_meta = $a->getMetaProperties();

$b_id   = $b->Id;
$b_name = $b->Name;
$b_data = $b->Data;

print_r([
    'a_set' => $a,
    'b_set' => $b,
    'a_get' => ['id' => $a_id, 'name' => $a_name, 'data' => $a_data, 'meta' => $a_meta],
    'b_get' => ['id' => $b_id, 'name' => $b_name, 'data' => $b_data],
    'd' => $d,

    // true
    'b == $d[1]' => $b == $d[1],

    // false
    'b === $d[1]' => $b === $d[1],

    'exceptions' => array_map(function (Throwable $ex) { return $ex->getMessage(); }, $exceptions),
]);
